# VictoriaLogs single-node.
nameOverride: vls

server:
  retentionPeriod: 14d
  persistentVolume:
    enabled: true
    storageClassName: yc-network-ssd
    size: 20Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: "1"
      memory: 1Gi

