apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-app
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt-app
  template:
    metadata:
      labels:
        app: nuxt-app
    spec:
      containers:
        - name: nuxt-app
          image: ghcr.io/patsevanton/victorialogs-alerting-by-error-panic-nuxt:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nuxt-app
  namespace: apps
spec:
  selector:
    app: nuxt-app
  ports:
    - port: 3000
      targetPort: 3000
